# Machine-readable rule map. Generated by /create-harness; edits require human review.
# severity: block = CI fails and merge is blocked · warn = reported, not blocking
project: "{{PROJECT}}"
rules:
  - id: INV-001
    statement: "{{testable statement}}"
    source: human            # human | doc | ai-inferred
    tier: 3                  # 1 static | 2 compile | 3 test | 4 human
    enforcer: "{{path/to/test-or-script}}"
    severity: block
    red_evidence: "{{date + what was sabotaged + observed failure}}"
meta:
  ci_workflow: ".github/workflows/harness.yml"
  locked_paths:
    - ".harness/"
    - "scripts/harness/"
    - "{{harness test dir(s)}}"
    - ".github/workflows/harness.yml"
