package com.karate.tournament.entity.enums;

public enum ScoreEventType {
  TIMER_START,
  TIMER_STOP,
  TIMER_SET,
  SCORE_DELTA,
  SCORE_EXCHANGE,
  PENALTY,
  SENSHU,
  SENSHU_REVOKE,
  VIDEO_REVIEW_REQUEST,
  VIDEO_REVIEW_RESOLVE,
  MEDICAL_START,
  MEDICAL_RESOLVE,
  HANTEI_DECISION,
  VR,
  KATA_VOTE,
  KATA_REVEAL,
  STATUS_CHANGE,
  RESULT_CONFIRMED,
  MANUAL_CORRECTION
}
